# Generated by Django 3.2.8 on 2021-10-09 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillVendors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Vendors first name', max_length=45)),
                ('address', models.CharField(help_text='Vendors address', max_length=45)),
                ('postalcode', models.CharField(help_text='Vendors postalcode', max_length=45)),
                ('city', models.CharField(help_text='Vendors city', max_length=45)),
                ('phone', models.CharField(help_text='Vendors phone number', max_length=12)),
                ('email', models.EmailField(help_text='Vendors email address', max_length=254)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HousingAssociation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='HA name', max_length=45)),
                ('address', models.CharField(help_text='HA address', max_length=198)),
                ('postalcode', models.CharField(help_text='HA postalcode', max_length=6)),
                ('city', models.CharField(help_text='HA city', max_length=45)),
                ('phone', models.CharField(help_text='HA phone number', max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('comments', models.TextField(help_text='Comments', max_length=1000)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Landlords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Landlords first name', max_length=45)),
                ('surname', models.CharField(help_text='Landlords last name', max_length=45)),
                ('phone', models.CharField(help_text='Landlords phone number', max_length=12)),
                ('email', models.EmailField(help_text='Landlords email address', max_length=254)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tenants',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Tenant first name', max_length=45)),
                ('surname', models.CharField(help_text='Tenant last name', max_length=45)),
                ('address', models.CharField(help_text='Tenant address', max_length=198)),
                ('postalcode', models.CharField(help_text='Tenant postalcode', max_length=6)),
                ('city', models.CharField(help_text='Tenant city', max_length=45)),
                ('phone', models.CharField(help_text='Tenant phone number', max_length=12)),
                ('email', models.EmailField(help_text='Tenant email address', max_length=254)),
                ('comments', models.TextField(help_text='Comments', max_length=1000)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(help_text='User login', max_length=45)),
                ('password', models.CharField(help_text='User password', max_length=198)),
                ('name', models.CharField(help_text='User first name', max_length=45)),
                ('surname', models.CharField(help_text='User last name', max_length=45)),
                ('type', models.CharField(help_text='Account type: 0 - user, 1 - admin', max_length=1)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Property name', max_length=45)),
                ('address', models.CharField(help_text='Property address', max_length=198)),
                ('postalcode', models.CharField(help_text='Property postalcode', max_length=6)),
                ('city', models.CharField(help_text='Property city', max_length=45)),
                ('kw_number', models.CharField(help_text='Numer KW', max_length=15)),
                ('house_association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.housingassociation')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LeaseAgreement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DateField(help_text='Lease agreement beginning date')),
                ('end', models.DateField(help_text='Lease agreement ending date')),
                ('value', models.DecimalField(decimal_places=2, help_text='Lease agreement value', max_digits=19)),
                ('comments', models.TextField(help_text='Comments', max_length=1000)),
                ('type', models.CharField(help_text='Lease agreement type: 0 - normal, 1 - notarial', max_length=1)),
                ('landlords', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.landlords')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.property')),
                ('tenants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tenants')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Bills name', max_length=198)),
                ('agreement_number', models.CharField(help_text='Agreement number', max_length=45)),
                ('start', models.DateField(help_text='Agreement beginning date')),
                ('duration', models.IntegerField(help_text='Duration in months')),
                ('end', models.DateField(help_text='Agreement ending date')),
                ('phone', models.CharField(help_text='Landlords phone number', max_length=12)),
                ('email', models.EmailField(help_text='Landlords email address', max_length=254)),
                ('bill_vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.billvendors')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.property')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
