# Generated by Django 3.2.8 on 2021-10-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211015_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housingassociation',
            name='comments',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
