# Generated by Django 3.2.8 on 2021-10-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_housingassociation_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housingassociation',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='housingassociation',
            name='phone',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
