# Generated by Django 3.2.8 on 2021-10-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211017_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billvendors',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='billvendors',
            name='phone',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='landlords',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='landlords',
            name='phone',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='leaseagreement',
            name='comments',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='property',
            name='kw_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='comments',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='phone',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
