# Generated by Django 3.2.8 on 2021-11-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_property_ha_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='ha_choice',
            field=models.CharField(choices=[(14, 'Spółdzielnia1'), (15, 'Spółdzielnia 2'), (16, 'flatman'), (17, 'Perspektywa'), (18, 'ŁSM'), (42, 'ŁSM'), (43, 'ŁSM 43'), (44, 'ŁSM'), (45, 'ŁSM'), (46, 'ŁSM'), (47, 'ŁSM'), (48, 'ŁSM'), (49, 'Spółdzielnia Testowa 0')], max_length=2),
        ),
    ]
