# Generated by Django 3.2.8 on 2021-11-23 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_property_ha_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='ha_choice',
        ),
    ]
