# Generated by Django 3.2.8 on 2021-11-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_property_ha_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseagreement',
            name='agreement_number',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
