# Generated by Django 3.2.8 on 2021-11-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_leaseagreement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaseagreement',
            name='type',
            field=models.IntegerField(choices=[(0, 'Zwykła'), (1, 'Notarialna')], verbose_name=[(0, 'Zwykła'), (1, 'Notarialna')]),
        ),
    ]
