# Generated by Django 3.2.8 on 2021-11-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_leaseagreement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaseagreement',
            name='type',
            field=models.CharField(choices=[(0, 'Zwykła'), (1, 'Notarialna')], default=0, max_length=1),
        ),
    ]
