# Generated by Django 3.2.8 on 2021-12-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_leaseagreement_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseAgreement_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=45)),
            ],
        ),
    ]
