# Generated by Django 3.2.8 on 2021-12-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20211218_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaseagreement',
            name='agreement_number',
            field=models.CharField(max_length=45),
        ),
    ]
