# Generated by Django 3.2.8 on 2021-12-21 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_leaseagreement_agreement_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaseagreement',
            old_name='agreement_number',
            new_name='la_number',
        ),
    ]
