# Generated by Django 3.2.8 on 2021-12-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_rename_agreement_number_leaseagreement_la_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingAssociation_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
    ]
