# Generated by Django 3.2.8 on 2021-12-27 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_housingassociation_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housingassociation_type',
            options={'ordering': ['name']},
        ),
    ]
