# Generated by Django 3.2.8 on 2021-12-27 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_housingassociation_type_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingassociation',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.housingassociation_type'),
        ),
    ]
