# Generated by Django 3.2.8 on 2022-02-02 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_housingassociation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='house_association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.housingassociation'),
        ),
    ]
